apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://0.0.0.0:9411/api/v2/spans"
  metric:
    enabled: true